{
 "title": "TITLE",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL ACCUMULATED PER UNIT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "price_volume",
     "query": "SELECT SUM(gain) FROM (SELECT sell_price - buy_price as gain FROM session WHERE \"algo\" = 'ALGO' AND \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2')",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CURRENT PRICE PER UNIT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "price_volume",
     "query": "SELECT \"price\" FROM \"price_volume\" WHERE (\"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    }
   ]
  },
  {
   "title": "FIRST BUY PRICE PER UNIT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "price_volume",
     "query": "SELECT price FROM trade WHERE \"algo\" = 'ALGO' AND \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2' ORDER by time ASC limit 1",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "IL PRIMO BUY .....(ma12>ma15 ).........price>price 2min ago...........( 2-4-10 ) 2 min ago",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BUY ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "query": "SELECT mean(\"price\") FROM \"trade\" WHERE (\"type\" = 'buy' AND \"algo\" = 'ALGO' AND  \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "buy" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "SELL ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "query": "SELECT mean(\"price\") FROM \"trade\" WHERE (\"type\" = 'sell' AND \"algo\" = 'ALGO' AND  \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "sell" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "PRICE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "query": "SELECT mean(\"price\") FROM \"price_volume\" WHERE (\"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "4" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma17",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "17" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma30",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "15" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "la PRIMA VENDITA !",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BUY ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "buy" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "SELL ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "sell" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "PRICE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "11" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "4" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "7" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma43",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "43" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "ma16",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "16" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Candle Graph",
   "type": "ilgizar-candlestick-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "open",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT first(\"price\") FROM \"price_volume\" WHERE (\"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(linear)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "close",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"price\") FROM \"price_volume\" WHERE (\"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(linear)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"price\") FROM \"price_volume\" WHERE (\"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(linear)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"price\") FROM \"price_volume\" WHERE (\"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(linear)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "APRE LA GABBIA ..........ma100_2min_ago........etc.",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BUY ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "query": "SELECT mean(\"price\") FROM \"trade\" WHERE (\"type\" = 'buy' AND \"algo\" = 'ALGO' AND \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "buy" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "SELL ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "query": "SELECT mean(\"price\") FROM \"trade\" WHERE (\"type\" = 'sell' AND \"algo\" = 'ALGO' AND \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "sell" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "7" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "11" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "4" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA16",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA41",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "41" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "15" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "BUY -----ma2 >ma2 2min ago..E...ma4>ma4 2min ago....E...ma11>ma11 2min ago....E....ma8>ma8 2min...E...ma11-ma24",
   "type": "graph",
   "description": "LA FERRARI\n(ma2 >ma2 2min ago E ma4>ma4 2min ago)\n\nSANT' ANTONIO \nma13 > ma13 2 min ago",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BUY ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "query": "SELECT mean(\"price\") FROM \"trade\" WHERE (\"type\" = 'buy' AND \"algo\" = 'ALGO' AND \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "buy" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "SELL ACTION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trade",
     "query": "SELECT mean(\"price\") FROM \"trade\" WHERE (\"type\" = 'sell' AND \"algo\" = 'ALGO' AND  \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "sell" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "PRICE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "11" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "4" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "7" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    },
    {
     "alias": "MA16",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "price_volume",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "16" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "EXCHANGE" },
      { "condition": "AND", "key": "symbol_1", "operator": "=", "value": "SYMBOL_1" },
      { "condition": "AND", "key": "symbol_2", "operator": "=", "value": "SYMBOL_2" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "MACD",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(proper) - moving_average(mean(proper), 9) as macd FROM (SELECT moving_average(mean(price), 12) - moving_average(mean(price), 26) as proper FROM price_volume WHERE exchange = 'EXCHANGE' and symbol_1 = 'SYMBOL_1' and symbol_2 = 'SYMBOL_2' and time > now() - 24h GROUP BY time(1m) fill(previous)) WHERE time > now() - 1d GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "SESSIONS MADE",
   "type": "table-old",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "measurement": "trade",
     "query": "SELECT session, buy_time, buy_price as buy, sell_time, sell_price as sell, sell_price - buy_price as diff, ((sell_price - buy_price) * 100 / buy_price) as percentage FROM session WHERE \"algo\" = 'ALGO' AND  \"exchange\" = 'EXCHANGE' AND \"symbol_1\" = 'SYMBOL_1' AND \"symbol_2\" = 'SYMBOL_2' ORDER BY time",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "sell" }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "collapsed": true
  }
 ]
}