version: '3'

services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        ports:
            - "8086:8086"
        volumes:
            - ./data/influxdb:/var/lib/influxdb
        environment:
            - TZ=Europe/Amsterdam
            - INFLUXDB_ADMIN_ENABLED="true"
            - INFLUXDB_DB=crypto_trader_bot
            - INFLUXDB_ADMIN_USER=root
            - INFLUXDB_ADMIN_PASSWORD=root
        restart: always

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - TZ=Europe/Amsterdam
            - GF_SECURITY_ADMIN_PASSWORD=s3cr3t
        restart: always
        depends_on:
            - influxdb
